version: "3.8"
services:
  thepostgres:
    image: postgres
    restart: on-failure
    container_name: thepostgres
    volumes:
      - /etc/letsencrypt/live/georgejmx.dev:/app/cert/live/georgejmx.dev:ro
      - /etc/letsencrypt/archive/georgejmx.dev:/app/cert/archive/georgejmx.dev:ro
    env_file:
      - docker.env
    ports:
      - "5432:5432"
  app:
    build: .
    env_file:
      - docker.env
    ports:
      - "80:3000"
      - "443:3000"
    restart: on-failure
