version: "3.8"

volumes:
  georgejmx_data:
    name: georgejmx_data

services:
  thepostgres:
    image: postgres
    restart: on-failure
    container_name: thepostgres
    env_file:
      - docker.dev.env
  app:
    build:
      context: ../.
    restart: on-failure
    env_file:
      - docker.dev.env
    volumes:
      - georgejmx_data:/var/lib/postgresql/data
    ports:
      - "80:3000"
      - "443:3000"
