name: Validate

on: [push]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Initialise Node.js v20
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - run: npm ci
            - run: npm run lint:ci
            - run: npm run compile
            - run: npm run test:ci
            - run: cd frontend; npm ci; npm run build
