name: Validate

on: [push]

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Check Bun Environment
              uses: oven-sh/setup-bun@v1
            - run: bun install
            - run: bun lint:ci
            - run: bun compile
            - run: bun jest-test:ci
